---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Sendroid"
keywords:    "sendroid, android, firefox, chrome, share, nachiketa, nachiketa das, atekihcan, sendroid, github, blog"
description: "Easily share text or link from browser to android device"
source_link: ""
favicon:     "img/favicon-sendroid.png"
touch_icon:  "img/apple-sendroid.png"
google_analytics_key: UA-57470252-1


### template colors, used site-wide via css ###
colors:
  black:    		'#111111'
  white:	    	'#f8f8f8'
  andro-blue:		'#0099cc'
  andro-blue-li:	'#33b5e5'
  andro-violet:		'#9933cc'
  andro-violet-li:	'#aa66cc'
  andro-green:		'#669900'
  andro-green-li:	'#99cc00'
  andro-yellow:		'#ff8800'
  andro-yellow-li:	'#ffbb33'
  andro-red:		'#cc0000'
  andro-red-li: 	'#ff4444'
  sendroid:         '#27bec4'
  sendroid-li:      '#ccfeff'
  sendroid-da:      '#00888C'
